### ISSUE TITLE
Some ncRNAs don't have ensembl field, but apparently they do have ensembl ids.

### ISSUE THREAD

**Issue by logust79** [SuLab/mygene.info#8]
I do not know whether this is a desired feature?
`https://mygene.info/v3/gene/7012?fields=all` has no `ensembl` field, but it does have an ensembl id: ENSG00000270141
And these 'genes' lack hg38 coordinates as well.

**Comment by newgene** [comment]
Hi @logust79, Ensembl gene [ENSG00000270141](http://uswest.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000270141) and NCBI EntrezGene [7012](https://www.ncbi.nlm.nih.gov/gene/7012) do look like the same gene, but unfortunately, they are not mapped to each other based on Ensembl. This can be verified from Ensembl's BioMart interface, [click this link](http://uswest.ensembl.org/biomart/martview/7cb790f6eab05cc5d1c1f6ff2b147322?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.feature_page.ensembl_gene_id|hsapiens_gene_ensembl.default.feature_page.ensembl_transcript_id&FILTERS=hsapiens_gene_ensembl.default.filters.with_entrezgene.only|hsapiens_gene_ensembl.default.filters.entrezgene.%227012%22&VISIBLEPANEL=resultspanel) (make sure to hit the "results" button to execute the query). Because of that, these two are considered two different genes from MyGene.info as well:

https://mygene.info/v3/gene/7012

https://mygene.info/v3/gene/ENSG00000270141

If later, Ensembl decides to map these two genes with each other, these two gene objects will be merged in MyGene.info as well.

**Comment by logust79** [comment]
Thanks for your explanation.
